baseURL = "https://bimnaepsdelugo.es"
languageCode = "es-es"
defaultContentLanguage = "es"
title = "BIM na EPS de Lugo"
theme = "hugo-theme-casper"
paginate = 5
Copyright = "All rights reserved"
canonifyurls = true

[params]
description = "BIM significa 'building information modelling'<br /> Se queres saber máis acerca do que é o importante que pode ser para a tua carreira <br /> sigue navegando nesta páxina"
authorlocation = "authorlocation"
cover = "images/BIMbeginnerHeader.jpg"
## save the image you want to use as background picture in directory "./static/images"
author = "BIM"
# logo = "images/logo.png"
## save the image you want to use as website logo in directory "./static/images"(delete this line when editing)
githubName = "muchomuchacho"
# linkedinName = "BIM"
email = "bim@eps.es"
hideHUGOSupport = true

# here are the buttons on the menu
[[menu.main]]
name = "Inicio" # Button will display as "Home"
weight = 100 # the weight decides the position of the button (higher or lower)
identifier = "home"
pre = "<br />"
url = "/"

[[menu.main]]
name = "Contacto"
weight = 1
identifier = "contact" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/contact"

[[menu.main]]
name = "Quen somos..."
weight = 40
identifier = "about" # this button will refer to a markdown file named "about" in the content folder
pre = "<br />"
url = "/about"

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
