baseURL: "https://bimnaepsdelugo.es"
languageCode: "es-ES"
defaultContentLanguage: "es"
title: "BIM na EPS dE Lugo"
theme: "hugo-mucho-theme"
paginate: 2
pluralizelisttitles: false
Copyright: "Todolos dereitos reservados"
canonifyurls: true

params:
  description: |
    BIM: PRESENTE E FUTURO DUNHA NOVA METODOLOXÍA COLABORATIVA PARA AS GRANDES OBRAS DE ENXEÑARÍA. PERSPECTIVA ACADÉMICA E DE EMPRESAS.


  authorlocation: "Lugo, España"
  cover: "images/w-2000_h-1100_m-cover_s-any__tunnelling.jpeg"
  author: "Pardiñas"
  logo: "images/2021-03-31_13-05.png"
  ## save the image you want to use as website logo in directory "./static/images"(delete this line when editing)
  # githubName: "bimnaepsdelugo"
  email: "cursosdeveran@usc.es"
  hideHUGOSupport: true

# here are the buttons on the menu
menu:
  main:
    - name: "Inicio"  # Button will display as "Home"
      weight: 100  # the weight decides the position of the button (higher or lower)
      identifier: "home"
      pre: "<br />"
      url: "/"
    - name: "Quenes somos"
      weight: 40
      identifier: "about"  # this button will refer to a markdown file named "about" in the content folder
      pre: "<br />"
      url: "/about"
    - name: "Contacto"
      weight: 1
      identifier: "contact"  # this button will refer to a markdown file named "contact" in the content folder
      pre: "<br />"
      url: "/contact"

permalinks:
  post: "/:slug/"

sitemap:
  ChangeFreq: ""
  Filename: "sitemap.xml"
  Priority: "-1"
