baseURL: "https://bimnaepsdelugo.es"
languageCode: "es-ES"
defaultContentLanguage: "es"
title: "BIM na EPS de Lugo"
theme: "hugo-theme-casper"
paginate: 5
Copyright: "All rights reserved"
canonifyurls: true

params:
  description: |
    BIM significa 'building information modelling'.  
    Se queres saber máis acerca do que é, e o importante que pode ser para a tua carreira
    sigue navegando nesta páxina
    
  authorlocation: "Lugo, Espana"
  cover: "images/w-2000_h-1100_m-cover_s-any__tunnelling.jpeg"
  author: "EPS BIM"
  # logo = "images/logo.png"
  ## save the image you want to use as website logo in directory "./static/images"(delete this line when editing)
  githubName: "bimnaepsdelugo"
  email: "bim@eps.es"
  hideHUGOSupport: false
  
# here are the buttons on the menu
menu:
  main:
    - name: "Inicio"  # Button will display as "Home"
      weight: 100  # the weight decides the position of the button (higher or lower)
      identifier: "home"
      pre: "<br />"
      url: "/"
    - name: "Quen somos..."
      weight: 40
      identifier: "about"  # this button will refer to a markdown file named "about" in the content folder
      pre: "<br />"
      url: "/about"
#     - name: "Contacto"
#       weight: 1
#       identifier: "contact"  # this button will refer to a markdown file named "contact" in the content folder
#       pre: "<br />"
#       url: "/contact"

permalinks:
  post: "/:slug/"

sitemap:
  ChangeFreq: ""
  Filename: "sitemap.xml"
  Priority: "-1"
