name = "Casper"
license = "MIT"
licenselink = "https://github.com/muchomuchacho/hugo-mucho-theme/blob/master/LICENSE.md"
description = "Casper style theme theme"
homepage = "https://bimnaepsdelugo.es"
tags = ["cursos"]
features = ["disqus", "google analytics","share"]
min_version=0.25

[author]
  name = "muchomuchacho"
  homepage = "https://bimnaepsdelugo.es"

[original]
  name = "Casper"
  homepage = "https://github.com/TryGhost/Casper"
  repo = "https://github.com/TryGhost/Casper"
